CREATE TABLE usuarios(
Id int NOT NULL AUTO_INCREMENT,
Nome VARCHAR(250) NOT NULL,
Email VARCHAR(250) NOT NULL,
Senha VARCHAR(250) NOT NULL,
UltimoLogin TIMESTAMP NOT NULL,
CONSTRAINT pk_usuarios_id PRIMARY KEY(Id)
);
